- examples/walkdir.rs
- src/lib.rs
- src/tests.rs
Imagine this use-case. One wants to do a scan of all folders and perform the same scan later and obtain the list of differences.
The scanning will produce two lists that are expensive to sort. It is more efficient to have WalkDir output a sorted list.
Currently WalkDir uses the iterator from `fs::read_dir`. The entries are used as is.
The proposed patch adds a boolean value `sort` that enables sorting of the entries.
This matches nicely with the behaviour of WalkDir when `max_open == 1`: all entries of the opened dir are read instantly. in addition, they are sorted.
A simple benchmark on a directory with one million files (warm cache) shows:
```
walkdir ~          2.0s
walkdir --sort ~   2.8s
walkdir ~ | sort  19.5s
```
> Add ability to sort the walked entries

- Cargo.toml
As far as I can tell these are only used for windows. With these changes it still builds and works on linux for me. Not tested on any other platform.
> only depend on windows deps on windows

- src/lib.rs
Since the minimum supported rustc version has this fix[1] we can
remove the reference.
[1] https://github.com/rust-lang/rust/pull/31630
> Remove reference to a bug which has been fixed

- src/lib.rs
- src/tests.rs
When given a root like `foo` where `foo` is a symlink, it should always
be followed. This behavior is consistent with `foo/`, which will also be
followed.
See also: https://github.com/BurntSushi/ripgrep/issues/256
> Fix bug reading root symlink.

- .travis.yml
- Cargo.toml
- appveyor.yml
- src/same_file.rs
- src/tests.rs
This modifies some of the test infrastructure so that more tests can
work on Windows. Specifically, we can now write tests that use symlinks
and still run on Windows.
We also clean up the implementation of `is_same_file` by reusing
types/functions from the kernel32 and winapi crates. Also, add a few
tests for this function.
> Various Windows related cleanups.

- src/lib.rs
> Fix typos in comments

- examples/walkdir.rs
- src/lib.rs
- src/tests.rs
#18 
Added ability to yield the contents of the directory before the
directory itself
> Added contents_first option

- src/lib.rs
- src/tests.rs
fixes: https://github.com/BurntSushi/walkdir/issues/37
> Renamed Iter to IntoIter

- Cargo.toml
fixes https://github.com/BurntSushi/walkdir/issues/36
> Added categories to Cargo.toml

- src/lib.rs
Fixes https://github.com/BurntSushi/walkdir/issues/38
> Renamed IterFilterEntry to FilterEntry

- Cargo.toml
- src/lib.rs
Typically the `# remember to update html_root_url` clause is added next to the `version` field in Cargo.toml as stated in [C-HTML-ROOT](https://github.com/brson/rust-api-guidelines#crate-sets-html_root_url-attribute-c-html-root)
But I did not know if the `#:version` comment was relevant (possibly part of some uncommited script?)
I'll be glad to fix it.
fixes https://github.com/BurntSushi/walkdir/issues/33
> Added html_root_url attribute

- Cargo.toml
Fixes #35
Doesn't add CI for OSX
> Add badges for travis-ci and appveyor to Cargo.toml

- .travis.yml
as mentioned in https://github.com/BurntSushi/walkdir/pull/52#issuecomment-311210665 the next backwards supported rust version is to be 1.16.0.
fixes https://github.com/BurntSushi/walkdir/issues/61
> Bumped the minimal required rust version to 1.16.0

- src/lib.rs
Add links specifically for the `DirEntry` docs as well as `filter_entry` in the root doc. Let me know if this needs further change or formatting.
Fixes #27.
> Add links to other items in DirEntry docs

- src/lib.rs
Fixes: #25 except for "examples on WalkDirIterator.skip_current_dir" because there is no unwrap()
> Use `?` in docs instead of unwrapping

- src/lib.rs
Fix to issue #29 
Add reference links in the WalkDir docs prose when mentioning other walkdir items:
- WalkDir::filter_entry
- WalkDir::min_depth
> Add links to other walkdir items in WalkDir docs

- examples/walkdir.rs
- src/lib.rs
- src/tests.rs
Currently it is not easy to sort entries alphabetically with directories first (which is most often the order in which we see files in tools), since sorter for `WalkDir::sort_by()` only provides file names. In this PR I have changed the code, so that the sorter accepts references to entries being sorted. Example usage:
```
extern crate walkdir;
fn main() {
use std::cmp::Ordering;
use walkdir::WalkDir;
// Paths sorted alphabetically with directories first
for e in WalkDir::new("./").sort_by(|a, b| match b.file_type().is_dir().cmp(&a.file_type().is_dir()) {
Ordering::Equal => a.file_name().cmp(b.file_name()),
o @ _ => o,
}).into_iter().filter_map(|e| e.ok()) {
println!("{}", e.path().display());
}
}
```
If this change would to be accepted, we have to also fix the documentation accordingly. …
> WalkDir sorter should accept whole dir entries instead of just file names

- src/lib.rs
for `Iter` (`Iterator::next()`), `FilterEntry` (`Iterator::next()`), and `DirEntry::metadata()`
For #24
> Extended documentation to include Errors section 

- src/lib.rs
Added a wrapper around this function that is deprecated.
Fixes #43.
> Remove re-export of is_same_file

- .travis.yml
In response to https://github.com/BurntSushi/walkdir/pull/60#issuecomment-311212136.
I think that testing a cross-platform lib on all main platforms makes sense for the libz blitz.
> Add osx build to .travis.yml

- src/lib.rs
> Document why unwraps won't fail

- src/lib.rs
> Derive Debug for public structs

- src/lib.rs
- src/unix.rs
Closes #46
Cherry pick from #53
I've made the following changes to @jeremielate's origin commits:
- Ensure the `unix` module is `use`d
> Unix-specific Extension trait

- README.md
- src/lib.rs
> Fix some docs mistakes 

- .travis.yml
Two linux builds using rust beta are being run on Travis.
Nightly isn't being tested.
> Duplicate rust beta being run, should be nightly

- src/lib.rs
> add example for converting to I/O error

- .travis.yml
- Cargo.toml
- README.md
- examples/walkdir.rs
- src/lib.rs
- src/tests.rs
- src/unix.rs
This PR contains a smattering of commits that should bring walkdir up to 2.0. Most commits are just polishing, but also:
1. The `DirEntryExt` trait wasn't actually exported. That's done now.
2. I optimized the symbolic link checking loop in an attempt to fix this [ripgrep bug](https://github.com/BurntSushi/ripgrep/issues/633). It's not related to 2.0, but I was in the code and it was an easy enough change.
3. Upgrade to use `same-file 1.0`, which was just released.
> towards 2.0

- Cargo.toml
This is a rollup of #86 and #87.
cc @ignatenkobrain (The quickcheck and rand deps are linked since rand is a public dependency of quickcheck.)
> deps: bump quickcheck to 0.6 and rand to 0.4

- src/lib.rs
When reading the docs on docs.rs, I found a couple of broken links:
- The first link to `WalkDir` on https://docs.rs/walkdir/2.0.1/walkdir/#from-the-top
- The link to `follow_links` on https://docs.rs/walkdir/2.0.1/walkdir/index.html#example-follow-symbolic-links
Interestingly enough, when previewing the built docs locally I didn't see these problems - it could be that it's possible that browsers (I tested on Safari and Firefox on Mac) treat filenames as case-insensitive and URLs as case-sensitive? I'm not sure why the problem happens in the first place, but these changes bring the capitalization of the doc links in line with that of the `WalkDir` struct, so that should help.
Hope this helps!
> Fixing broken links when reading docs online

- examples/walkdir.rs
- src/lib.rs
This change will keep "pretty" error messages even when the error has been converted to `io::Error`.
Example:
```
Pretty error: IO error for operation on /path/does-not-exist: No such file or directory (os error 2)
```
The standard library returns `std::io::Error` for failed filesystem operations. `io::Error` is an extremely lightweight type which typically uses `&'static str` for its "caused-by" `error` argument to keep it even _more_ lightweight. Many filesystem operations _could_ include path information, but they don't -- probably for performance and compatibility reasons.
However, the [type itself](https://doc.rust-lang.org/std/io/struct.Error.html) makes no requirements on what the "caused-by" `error` type is. When the type is returned unmodified from `std::fs` or `std::path` …
> Keep context when converting to io::Error

- src/lib.rs
A big potential question on the reader's mind when reviewing these docs is "what will the paths returned by the iterator be relative to?"  This is the one example on the page which shows output that could potentially answer that question, and to only see filenames is needlessly discouraging.
> improve stdout in contents_first doc example

- src/lib.rs
This PR fixes a performance regression introduced by 0f4441f9. We had accidentally introduced an additional stat call for every directory entry on Windows.
> fix performance regression

- README.md
- src/lib.rs
> Fix syntax highlighting in README

- src/lib.rs
This fixes compilation on Redox
> Fix issue with direntry clone on non-unix and non-windows

- src/lib.rs
This pull requests adds `fn into_path(self) -> PathBuf` to `DirEntry`.
The use case for this is that I have an API like this:
```rust
fn from_paths<I: Iterator<Item = AsRef<Path>>>(paths: I)
```
I would like to be able to pass in something like this:
```rust
WalkDir::new(dir).into_iter().map(|e| e.unwrap().path())
```
Unfortunately that does not work, I have to make a copy:
```rust
WalkDir::new(dir).into_iter().map(|e| PathBuf::from(e.unwrap().path()))
```
This is wasteful; we allocate a pathbuf and copy the path into it, only to destroy the original immediately afterwards. With the proposed `into_path`, this is possible without the extra copy.
I have a small program that basically does this:
```rust
let dir = env::args().nth(1).unwrap();
let ext = OsStr::new("foo");
let wd = …
```
> Add DirEntry::into_path method

- Cargo.toml
- examples/walkdir.rs
- src/lib.rs
- src/tests.rs
- src/windows.rs
This commit includes a new method, `same_file_system`, which when
enabled, will cause walkdir to only descend into directories that are on
the same file system as the root path.
Closes #8, Closes #107
---
While this PR retains the authorship of #107, this ended up requiring significant refactoring:
* Instead of wringing our hands over uncloneable I/O errors, we simply delay the discovery of the root file path's device number until the first call to `next`, and if an error comes up there, we return it and quit iteration. This also eliminates a redundant store of the root file path.
* We make sure walkdir continues to compile on non-Unix/non-Windows platforms. If `same_file_system` is used on an unsupported platform, then an error is returned.
* Fix a bug in the behavior of the program. The …
> walkdir: add option to stay on same file system

- src/lib.rs
- src/tests/recursive.rs
With it it's possible to control whether symlinks in the traversal root are followed, while defaulting to 'true' like before, or if they are handled like ordinary links.
Created in response to [this `cargo` issue](https://github.com/rust-lang/cargo/pull/11634).
> `follow_root_links()` in `WalkDir`.

- src/lib.rs
`IntoIter` and `FilterEntry<IntoIter, P>` will return `None` once they returned `None`.
Implementing `FusedIterator` allows `Iterator::fuse` method to be optimized.
> Calling next on a fused iterator that has returned `None` once is guaranteed to return `None` again. This trait should be implemented by all iterators that behave this way because it allows optimizing `Iterator::fuse`.
>
> --- <https://doc.rust-lang.org/1.45.2/std/iter/trait.FusedIterator.html>
I checked `next()` implementations lightly and they seem to be already fused.
> iterator: implement `FusedIterator`
